default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("DB_USERNAME") { "root" } %>
  password: <%= ENV.fetch("DB_PASSWORD") { "password" } %>
  host: <%= ENV.fetch("DB_HOST") { "db" } %>
  port: <%= ENV.fetch("DB_PORT") { 3306 } %>

development:
  <<: *default
  database: cinema_booking_development

test:
  <<: *default
  database: cinema_booking_test

production:
  <<: *default
  database: cinema_booking_production
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>
